config/routes.rb
Rails.application.routes.draw do

  resources :citations

  resources :citations do
  	resources :authors
	end

  root to: 'cv#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :citation
 
end

app/models/citation.rb
class Citation < ApplicationRecord
	has_many :authors, :dependent => :destroy
	accepts_nested_attributes_for :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save

    redirect_to authors_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :middle_name, :last_name)
    end
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  before_action :set_citation, only: [:edit, :update, :show, :destroy]
  
  include AuthorsHelper

  def index
    @citations = Citation.includes(:authors)
  end

  def new
    @citation = Citation.new
    1.times { @citation.authors.build }
  end

  def create
    @citation = Citation.new(citation_params)
    if @citation.save
      flash[:notice] = "Citation Created"
      
      redirect_to citations_path
    else
      render 'new'
    end
  end

  def update

    if @citation.update_attributes(citation_params)
      redirect_to @citation
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    flash[:notice] = "Citation was successfully deleted"
    @citation.destroy
    redirect_to citations_path
  end

  def show
  end

  private
    def set_citation
      @citation = Citation.find(params[:id])
    end

    def citation_params
      params.require(:citation).permit(:year, :title, :journal, :volume, :issue, :pages, :doi, authors_attributes: [ :first_name, :middle_name, :last_name ])
    end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  def index
  	@citations = Citation.includes(:authors)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/citations/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/citations/_form.erb
<h1>Add New Citation</h1>

<%= form_for @citation do |f| %>

	<% if @citation.errors.any? %>
		<% @citation.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
		
	<div class="form-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :journal %><br/>
		<%= f.text_field :journal, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :year %><br/>
		<%= f.text_field :year, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :volume %><br/>
		<%= f.number_field :volume, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :issue %><br/>
		<%= f.number_field :issue, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :pages %><br/>
		<%= f.text_field :pages, class: 'form-control'  %><br/>
	</div>

	<div class="form-group">
		<%= f.label :doi %><br/>
		<%= f.text_field :doi, class: 'form-control'  %><br/>
	</div>

	<h3>Add New Author</h3>
		<% @count = 0 %>

		<%= f.fields_for :authors do |a| %>
	    <h5>Author <%= @count += 1 %></h5><br/>
	    <div class="form-group">
				<%= a.label :first_name %><br/>
				<%= a.text_field :first_name, class: 'form-control'  %><br/>
			</div>

			<div class="form-group">
				<%= a.label :middle_name %><br/>
				<%= a.text_field :middle_name, class: 'form-control'  %><br/>
			</div>

			<div class="form-group">
				<%= a.label :last_name %><br/>
				<%= a.text_field :last_name, class: 'form-control'  %><br/>
			</div>

	  <% end %>

	<%= f.submit "Submit", class: 'btn btn-primary' %>
	<%= link_to "Cancel", citations_path, class: 'btn btn-default' %>

<% end %>

app/views/citations/create.html.erb
<h1>Citations#create</h1>
<p>Find me in app/views/citations/create.html.erb</p>

app/views/citations/destroy.html.erb
<h1>Citations#destroy</h1>
<p>Find me in app/views/citations/destroy.html.erb</p>

app/views/citations/edit.html.erb
<%= render "form" %>

app/views/citations/index.html.erb
<%= render "layouts/citations" %>

app/views/citations/new.html.erb
<%= render "form" %>

app/views/citations/show.html.erb
<p>
  <strong>Name:</strong>
  <%=h @citation.title %>
</p>

<ol>
  <% for author in @citation.authors %>
  <li><%= h author.first_name %></li>
  <% end %>
</ol>

<p>
  <%= link_to "Edit", edit_citation_path(@citation) %> |
  <%= link_to "Destroy", @citation, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", citations_path %>
</p>

app/views/citations/update.html.erb
<h1>Citations#update</h1>
<p>Find me in app/views/citations/update.html.erb</p>

app/views/cv/index.html.erb
<header>
	<div class="row">
	  <div class="col d-flex justify-content-center">
	    <h1>Matthew E. Gitelis, B.S.</h1>
	  </div>
	</div>
	<div class="row">
	  <div class="col d-flex justify-content-center">
	    <h6>1148 W. Grand Ave. Unit #2, Chicago, IL 60642</h6>
	  </div>
	</div>
	<div class="row">
	  <div class="col d-flex justify-content-center">
	    <h6>Cell: (630) 290-8670 | Email: <%= mail_to 'matthew.gitelis@gmail.com' %></h6>
	  </div>
	</div>	
</header>
<section class='row'>
	<div class="col">
		<h3>Education</h3>
			<article>
				Rush Medical College
			</article>
		</div>
</section>
<section class='row'>
	<div class="col">
		<%= render 'layouts/citations' %>	
	</div>
</section>

app/views/layouts/_citations.erb
<h3>Peer-Reviewed Publications</h3>
  <article>
    <ol>
      <% @citations.each do |citation| %>
        <li><% citation.authors.each do |author| %>
          <%= author.first_name %>
          <%= author.middle_name %>
          <%= author.last_name %>

        <% end %>
        <%= citation.title %></li>
        <%= link_to "Edit", edit_citation_path(citation) %>
        <%= link_to 'Delete', citation_path(citation), method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>
    </ol>
  </article>

app/views/layouts/_header.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" <%= link_to image_tag("/assets/mg_logo.png", height: '30'), root_path %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" <%= link_to 'Citations', citations_path %></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add New</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" <%= link_to 'Citation', new_citation_path %></a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matthew Gitelis CV</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>